FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Magiqspark API

It is a collection of API end points allowing consumers to work with its entities.

## Scales Collection [/Scale s]

### List All Scales [GET]

+ Response 200 (application/json)

        [
            {
                "Name ": "Personal",
                "Description" : "Personal Scale",
                "Created at": "2015-08-05T08:40:51.620Z"
            }
        ]

### Create a New Scale  [POST]

You may create your own Scale  using this action. It takes a JSON
object containing Scale details

+ Request (application/json)

        {
            "Name ": "Name of the scale",
            "Descripton": "Details about the scale"
        }

+ Response 201 (application/json)

    + Headers

            Location: /Scale s/2

    + Body

            {
                "Name ": "Personal",
                "Description" : "Personal Scale",
                "Created at": "2015-08-05T08:40:51.620Z"
            }
            
## Behaviours Collection [/Behaviour s]

### List All Behaviours [GET]

+ Response 200 (application/json)

        [
            {
                "Behaviour ": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Behaviour  [POST]

You may create your own Behaviour using this action. It takes a JSON
object containing Behaviour details.

+ Request (application/json)

        {
            "Behaviour ": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /Behaviour s/2

    + Body

            {
                "Behaviour ": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Groups Collection [/Group s]

### List All Groups [GET]

+ Response 200 (application/json)

        [
            {
                "Group ": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Group  [POST]

You may create your own Group  using this action. It takes a JSON
object containing Group details

+ Request (application/json)

        {
            "Group ": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /Group s/2

    + Body

            {
                "Group ": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }